name: Add bookmark

on:
  repository_dispatch:
    types: recipe

jobs:
  add_bookmark:
    runs-on: macOS-latest
    name: Add bookmark
    # only continue if issue has "recipe" label
    if: contains( github.event.issue.labels.*.name, 'recipe')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bookmark action
        uses: ./
        with:
          fileName: _data/recipes.yml
      - name: Download the thumbnail image
        run: curl "${{ env.BookmarkImage }}" -o "img/${{ env.BookmarkImageOutput }}"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git commit -m  "Added ${{ env.BookmarkTitle }} to recipes.yml"
          git push
